import test from 'node:test';import assert from 'node:assert/strict';
import {formatPhone,parseVCF,matchContact,mergeContacts,validTarget,normalContact,validateBackup,esc,t9} from '../core-r4.js';
const card=(lines,version='3.0')=>['BEGIN:VCARD','VERSION:'+version,...lines,'END:VCARD'].join('\r\n');
test('BY progressive number formatting',()=>{assert.equal(formatPhone('+37529'),'+375 (29)');assert.equal(formatPhone('+375291234567'),'+375 (29) 123-45-67');assert.equal(formatPhone('+'),'+');assert.equal(formatPhone('*#06#'),'*#06#');});
test('safe target validation',()=>{assert.equal(validTarget('+12025550101'),true);for(const n of ['112','+112','+000000000','https://x','+1234567890123456','+1202;bad'])assert.equal(validTarget(n),false)});
test('single VCF Cyrillic and multiple numbers',()=>{const c=parseVCF(card(['N:Иванова;Анна;;;','FN:Анна Иванова','TEL;TYPE=CELL:+12025550101','TEL;TYPE=WORK:+12025550102'])).contacts[0];assert.equal(c.name,'Анна Иванова');assert.equal(c.phones.length,2);assert.equal(c.phones[0].label,'сотовый');});
test('vCard 4 tel URI and grouped Apple labels',()=>{const c=parseVCF(card(['FN:Test','item1.TEL;TYPE=cell:tel:+12025550101','item1.X-ABLabel:_$!<Мой номер>!$_'],'4.0')).contacts[0];assert.equal(c.phones[0].label,'Мой номер');assert.equal(c.phones[0].value,'+12025550101');});
test('folded FN and escaping',()=>{const c=parseVCF(card(['FN:Имя очень',' длинное\\, тест\\; проверка','TEL:+12025550101'])).contacts[0];assert.equal(c.name,'Имя оченьдлинное, тест; проверка');});
test('QP utf8 plus soft line wrap',()=>{const c=parseVCF(card(['FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=D0=90=D0=BD=','=D0=BD=D0=B0','TEL:+12025550101'],'2.1')).contacts[0];assert.equal(c.name,'Анна');});
test('QP windows1251',()=>{const c=parseVCF(card(['FN;CHARSET=windows-1251;ENCODING=QUOTED-PRINTABLE:=C0=ED=ED=E0'])).contacts[0];assert.equal(c.name,'Анна')});
test('base64 padding is not treated as QP soft break',()=>{const c=parseVCF(card(['FN:Photo','PHOTO;ENCODING=b;TYPE=JPEG:YWJjZA=='])).contacts[0];assert.equal(c.photo,'data:image/jpeg;base64,YWJjZA==');});
test('remote photo URL discarded; no implicit network fetch',()=>{const c=parseVCF(card(['FN:Photo','PHOTO;VALUE=URI:https://example.com/track.jpg'])).contacts[0];assert.equal(c.photo,'');});
test('SVG data photos rejected',()=>{const c=normalContact({name:'x',photo:'data:image/svg+xml;base64,AAAA'});assert.equal(c.photo,'');});
test('invalid VCF rejected',()=>assert.throws(()=>parseVCF('not a contact')));
test('empty card produces warning',()=>{const result=parseVCF(card(['NOTE:empty']));assert.equal(result.contacts.length,0);assert.equal(result.warnings.length,1)});
test('deduplicate by normalized name and numbers',()=>{const c=normalContact({name:'Анна',phones:[{value:'+12025550101'}]});const r=mergeContacts([c],[{...c,id:'different'}]);assert.equal(r.added,0);assert.equal(r.duplicates,1)});
test('T9 and Cyrillic search',()=>{const c=normalContact({name:'Есения',phones:[{value:'+12025550101'}]});assert.ok(matchContact(c,'есен'));assert.ok(matchContact(c,'25550'));assert.ok(matchContact(c,t9(c.name).slice(0,4)));});
test('backup sanitize and always reset to demo',()=>{const r=validateBackup({format:'mc-call-backup',schema:1,contacts:[],recents:[],settings:{mode:'live',operatorKey:'secret',backend:'https://evil',force:'+12025550101'}});assert.equal(r.settings.mode,'demo');assert.equal(r.settings.operatorKey,undefined);assert.equal(r.settings.backend,'');assert.equal(r.settings.force,'+12025550101')});
test('backup atomic input validation',()=>{assert.throws(()=>validateBackup({format:'mc-call-backup',schema:1,contacts:[],recents:[{at:'oops'}]}));});
test('text escaping prevents contact HTML execution',()=>assert.equal(esc('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;'));
test('2000 contacts parsed under a generous 2s bound',()=>{const v=Array.from({length:2000},(_,i)=>card(['FN:Person '+i,'TEL:+1202555'+String(i).padStart(4,'0')])).join('\n'),start=performance.now();assert.equal(parseVCF(v).contacts.length,2000);assert.ok(performance.now()-start<2000)});
